# Site settings
title: Andrew Lombardi Photography and Writing
short_title: Andrew Lombardi
email: andrew@mysticcoders.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Andrew Lombardi based in California, USA. Business
  owner, writer, photographer, speaker, trainer and father to a wonderful child.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andrewlombardi.com" # the base hostname & protocol for your site
twitter_username: kinabalu
github_username:  kinabalu

excerpt_separator: <!--more-->
# pagination
paginate: 3
paginate_path: "writings/page:num"


# Build settings
markdown: kramdown
highlighter: pygments
permalink: /writings/:title
# url: http://mysticcoders.com
disqus:
  config:
    - label: disqus_shortname
      value: 'andrewlombardi'
googleanalytics:
  account: UA-254925-10
plugins: [jekyll-paginate]
